### ISSUE TITLE
Support for specifying different values.yaml files

### ISSUE THREAD

**Issue by Nepo26** [fstaudt/helm-values#119]
It's possible to run `helm install -f <non_default_helm_file>.yaml <chart>`. When opening those _charts_ with the **helm-values** plugin, nothing happens and there is no comparison with the schema. 

It would be a great feature to be capable of defining a non default file name and/or folder that allows the schema to be used on those files.

---
Here is an example of what the directory tree may look like:
![image](https://github.com/fstaudt/helm-values/assets/36644628/548b54c0-937b-4912-baba-7b5793a824a2)

**Comment by fstaudt** [comment]
Hello @Nepo26 ,

JSON schema mappings provided by IntelliJ IDEA already allow to define JSON schemas for non-default files.

More information is provided in this issue: https://github.com/fstaudt/helm-values/issues/105#issuecomment-1643604160

**Comment by fstaudt** [comment]
@Nepo26 ,

what you try to accomplish is feasible with JSON schema mappings provided by IntelliJ IDEA.\
The file path pattern in your screenshot will apply JSON schema validation for all files in env folder.\
Schema file or URL should however be the JSON schema generated by helm-values plugin, not `../values.yaml`.\
JSON schema for values.yaml is generated by helm-values plugin as `.idea/json-schemas/<helm chart name>/aggregated-values.schema.json`.

It is indeed not really the right place to ask for this kind of support.\
JSON schema mappings are provided by IntelliJ IDEA, not by helm-values plugin.\
You can find more info on configuration of JSON schema mappings in IntelliJ IDEA documentation: 
https://www.jetbrains.com/help/idea/json.html#ws_json_schema_add_custom
