### ISSUE TITLE
Compatibility with IntelliJ >= 2024.1 EAP

### ISSUE THREAD

**Issue by garlikus** [fstaudt/helm-values#142]
The plugin is not compatible with IntelliJ 2024.1 EAP. IDE show: "Incompatible: requires IDE build 233.* or earlier".

**Comment by fstaudt** [comment]
@garlikus ,

thanks for creating the issue.

Compatibility with IntelliJ 2024.1 will be available with release 0.9.0.\
Release date for 0.9.0 is not defined yet, it should be somewhere in March.

**Comment by garlikus** [comment]
Thanks for the update.
