### ISSUE TITLE
Rada

### ISSUE THREAD

**Issue by RadaofTheLight** [fstaudt/helm-values#29]
https://github.com/apache/airflow/blob/31f6928d5ef963ff77a1f733ccc3017051fade37/chart/values.schema.json#L20-L23

**Comment by fstaudt** [comment]
Hello @RadaofTheLight ,

Can you provide more details in the description of the issue?

If you have an issue with content of Apache airflow schema, you should create an issue in their github repository.
The helm-values plugins are only extracting JSON schemas from dependency archives, they are not responsible for the content of the extracted schemas.
