### ISSUE TITLE
Helm values is not compatible with 2023.1 RC

### ISSUE THREAD

**Issue by gberche-orange** [fstaudt/helm-values#73]
> Plugin 'Helm Values' (version '0.6.0') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.8109.90

**Comment by fstaudt** [comment]
Hello @gberche-orange ,

thanks for creating the issue.

I'll release a new version of helm-values plugin shortly for compatibility with IJ 2023.1.0 .
