### ISSUE TITLE
Plugin complains about sops

### ISSUE THREAD

**Issue by anthonyalayo** [fstaudt/helm-values#82]
Thank you for the great plugin!

The one big pain I'm facing is that when I use sops, the plugin complains that it's invalid and tells me to remove it.

Is there a way we can support sops?

![image](https://user-images.githubusercontent.com/17555572/232250584-1571fcc4-5911-4cd6-bbe8-269fa8263941.png)

**Comment by fstaudt** [comment]
Hello @anthonyalayo ,

you can patch the JSON schemas generated by the plugin with a JSON patch to avoid those issues in your project.\
More info here: https://github.com/fstaudt/helm-values#patch-for-generated-json-schemas

For example, validation error on sops can be solved with following content in a file named `aggregated-values.schema.patch.json` and stored in same folder as Chart.yaml:
```json
[
  {
    "op": "add",
    "path": "/properties/sops",
    "value": {}
  }
]
```

To ensure that all developers benefit from the patch, the JSON patch file must be committed in the GIT repository.\
The same patch file must be committed in each repository in which you want to use sops.

Is this option sufficient for you ?

**Comment by anthonyalayo** [comment]
That works, thanks @fstaudt !
