### ISSUE TITLE
Use of version ranges for locally stored dependencies causes failure in JSON schemas aggregation

### ISSUE THREAD

**Issue by cm0s** [fstaudt/helm-values#93]
The plugin generates an error when a dependency point to a local file:

Example of a Chart.yaml dependency:
dependencies:
  - name: common
    version: ^1.0.0
    repository: file://../common

When executing the Refresh JSON schema the following stacktrace is raised: 

java.net.URISyntaxException: Illegal character in path at index 23: https://default/common/^0.0.0 at java.base/java.net.URI$Parser.fail(URI.java:2974) at java.base/java.net.URI$Parser.checkChars(URI.java:3145) at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227) at java.base/java.net.URI$Parser.parse(URI.java:3175) at java.base/java.net.URI. (URI.java:623) at io.github.fstaudt.helm.JsonSchemaGenerator.toRelativeUri(JsonSchemaGenerator.kt:138) at io.github.fstaudt.helm.JsonSchemaGenerator.putGlobalProperties(JsonSchemaGenerator.kt:75) at io.github.fstaudt.helm.JsonSchemaGenerator.generateValuesJsonSchema(JsonSchemaGenerator.kt:50) at io.github.fstaudt.helm.JsonSchemaAggregator.aggregate(JsonSchemaAggregator.kt:44) at io.github.fstaudt.helm.idea.service.HelmChartService.aggregate(HelmChartService.kt:59) at io.github.fstaudt.helm.idea.tasks.AggregateTask.run(AggregateTask.kt:13) at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429) at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186) at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604) at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679) at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60) at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173) at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699) at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cm0s** [comment]
I just saw you already took care of local repository addresses here https://github.com/fstaudt/helm-values/issues/30.

The problem is in fact related to the ^ in front of the version number which is not supported.

**Comment by fstaudt** [comment]
Hello @cm0s ,

thanks for reporting the issue.

Issue seems indeed related to use of version ranges in chart dependencies.\
Version ranges are currently not supported by the plugin, I still need to add it.

**Comment by fstaudt** [comment]
@cm0s 

generation of JSON schemas has been fixed in plugin for locally stored dependencies.

Issue https://github.com/fstaudt/helm-values/issues/94 has been created to support version ranges for dependencies having JSON schemas stored in external repositories:\
